### ISSUE TITLE
RestContext steps

### ISSUE THREAD

**Issue by theofidry** [jakzal/BehatRestExtension#9]
@jakzal this ticket is more a reminder for me you can assign it to me: I have a RestContext which extends behatch one for now but I would prefer to extend this one instead.

**Comment by jakzal** [comment]
I kind of have this context already. I just need to push other things first.

I'll get back to working on this extension sometime towards the end of the week (see #5 for roadmap).

**Comment by theofidry** [comment]
Yup I saw it. For now I'm using [my own contexts](https://github.com/in6pio/Incipio/tree/master/features/bootstrap) but I believe there is quite a few steps that are common enough to be handled by an extension. For now it's still under heavy development and your extension is so I have no precise idea about which step could be implemented by the RestContext.

**Comment by jakzal** [comment]
My opinion on this now is that we shouldn't provide default step definitions. We'd end up with the same issues as MinkExtension. This is not how scenarios should be written.

**Comment by theofidry** [comment]
Indeed it was more to have contexts for testing a REST API, but simply because Gherkin is [more convenient to write such tests](https://github.com/api-platform/core/blob/master/features/crud.feature), not to use Behat as a BDD tool. But I guess we can keep Behatch for that

**Comment by jakzal** [comment]
I see no issues if someone provides step definitions as another library that would use this extension. We could also put an example  context in the docs with an appropriate warning.

**Comment by theofidry** [comment]
Yep, I'll probably end up doing that at some point when I'll tackle REST API testing again
